repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        pass_filenames: false
        types: [python]
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [python]
      - id: pytest-check
        name: pytest-check
        entry: make test
        language: system
        pass_filenames: false
        types: [python]
